name: Reject merge commits
description: Fails if a PR branch contains merge commits

runs:
  using: "composite"
  steps:
    - name: Check for merge commits
      shell: bash
      run: |
        set -e

        git fetch origin main

        MERGES=$(git rev-list --merges origin/main..HEAD)
        if [ -n "$MERGES" ]; then
          echo "::error::Merge commits found in the branch:"
          git show --oneline --no-patch $MERGES
          exit 1
        fi